AWSTemplateFormatVersion: "2010-09-09"  # Specifies the CloudFormation template format version

Description: A simple EC2 instance with a name tag

# Parameters section defines input values for the template

Parameters:

  MyInstanceType:
    Type: String
    Description: Type of EC2 instance to launch (e.g., t2.micro, t2.small, t3.micro)
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
        # Restricts valid choices for the instance type

  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the existing key pair you'll use for SSH access to the instance

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the security group that defines network access rules for the instance

  MySubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the subnet within your VPC where the instance will be launched

# Resources section defines the infrastructure elements to be created

Resources:
  MyEc2Instance:  # Defines an EC2 instance resource
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref MySubnetId  # Reference the subnet ID from the parameter
      ImageId: ami-04a81a99f5ec58529  # Replace with the desired AMI ID
      InstanceType: !Ref MyInstanceType  # Reference the instance type from the parameter
      KeyName: !Ref MyKeyName  # Reference the key pair name from the parameter
      SecurityGroupIds:
        - !Ref MySecurityGroup  # Reference the security group ID from the parameter
      Tags:  # Add a tag to the instance
        - Key: Name
          Value: my-ec2-instance  # You can customize this tag value

# Outputs section defines values returned after successful stack creation

Outputs:
  InstanceId:
    Description: The ID of the launched EC2 instance
    Value: !Ref MyEc2Instance
  InstanceName:  # New output to display the assigned name
    Description: The name assigned to the EC2 instance through tag (may not be displayed directly)
    Value: !Ref MyTags  # This should be corrected to !Ref MyEc2Instance.Tags[0].Value
